package org.example.Enums.Comparators;

public enum UniversityComparators {
    UNIVERSITY_FULL_NAME_COMPARATOR,
    UNIVERSITY_SHORT_NAME_COMPARATOR,
    UNIVERSITY_MAIN_PROFILE_COMPARATOR,
    UNIVERSITY_YOF_COMPARATOR,
    UNIVERSITY_ID_COMPARATOR

}
